# Site settings
title: Magefoo - A professional Blog
description: Learn to play nice with Magento.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://magefoo.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: DFord
user_description: Magento Developer
email: magentofu@gmail.com
twitter_username: magentofu
github_username: magentofu 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Magento 1
    url: /magento1
  - title: Magento 2
    url: /magento2
  - title: Quickies
    url: /quickies
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
